env:
  node: true
parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:prettier/recommended
plugins:
  - "@typescript-eslint"
  - prettier
rules:
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: ^_
  "@typescript-eslint/no-implicit-any-catch":
    - error
    - allowExplicitAny: false
  curly:
    - warn
    - all
  no-constant-condition:
    - error
    - checkLoops: false
